blank_issues_enabled: false
contact_links:
  - name: Moonwell Discord Ticket System
    url: https://discord.gg/2rF59cz
    about: Ответы на интересующие вопросы! Поможет обеспечить более быстрые ответы, чем отправка проблемы на GitHub.
