name: 📩ㅤ Баг репорт
description: Создайте баг репорт для улучшения сервера
title: "ㅤ"
labels: "ㅤ"
body:
  - type: markdown
    attributes:
      value: Прежде чем писать о баге, пожалуйста, убедитесь, что о нем еще никто не сообщал.
  - type: textarea
    id: Opisanie-bagreporta
    attributes:
      label: Описание багрепорта
      description: Опишите обнаруженный багрепорт, укажите в своем описании как можно больше подробностей.
    validations:
      required: true
  - type: textarea
    id: kak-vosproizvesti-bag
    attributes:
      label: Как воспроизвести баг?
      description: Укажите последовательность действия для воспроизведения бага. База данных https://db.moonwell.su/
      value: |
        1.
        2.
        3.
        4.
        5.
        6.
        7.
        8.
        9.
        10.
    validations:
      required: true
  - type: textarea
    id: kak-doljno-rabotat
    attributes:
      label: Как должно работать?
      description: Используйте оффициальные источники https://wowpedia.fandom.com и https://www.wowhead.com/
    validations:
      required: true
  - type: textarea
    id: dopolnitelnaya-informacia
    attributes:
      label: Дополнительная информация, скриншоты и видео
      description: Используйте хостинг https://dropmefiles.com
  - type: dropdown
    id: client-version
    attributes:
      label: Игровая версия патча
      description: На какой Фазе возникла баг?
      options:
        - 2.0.3 (1ая фаза: The Karazhan, Lairs: Gruul and Magtheridon. Arena season - 1)
        - 2.0.3 (2ая фаза: The Eye, The Serpent Shrine Cavern. Arena season - 2)
        - 2.1.3 (3ая фаза: The Black Temple, The Hyjal Summit: Battle for Mount Hyjal. Arena season - 3)
        - 2.3.3 (4ая фаза: Zul'Aman)
        - 2.4.3 (5ая фаза: The Sunwell Plateau. Arena season - 4)
    validations:
      required: true
