name: 📩ㅤ Баг репорт
description: Создайте баг репорт для улучшения сервера
title: "ㅤ"
labels: "ㅤ"
body:
  - type: markdown
    attributes:
      value: Прежде чем писать о баге, пожалуйста, убедитесь, что о нем еще никто не сообщал.
  - type: textarea
    id: Opisanie-bagreporta
    attributes:
      label: Описание багрепорта
      description: Опишите обнаруженный багрепорт, укажите в своем описании как можно больше подробностей.
    validations:
      required: true
  - type: textarea
    id: kak-vosproizvesti-bag
    attributes:
      label: Как воспроизвести баг?
      description: Укажите последовательность действия для воспроизведения бага. База данных https://db.moonwell.su/
      value: |
        1.
        2.
        3.
        4.
        5.
        6.
        7.
        8.
        9.
        10.
    validations:
      required: true
  - type: textarea
    id: kak-doljno-rabotat
    attributes:
      label: Как должно работать?
      description: Используйте оффициальные источники https://wowpedia.fandom.com и https://www.wowhead.com/
    validations:
      required: true 
  - type: textarea
    id: suggested-workaround
    attributes:
      label: Suggested Workaround
      description: If you have a workaround please let us know
  - type: textarea
    id: crash-log
    attributes:
      label: Crash Log
      description: Provide us with the output from a core dump or when running 'mangosd' or 'realmd' through gdb
  - type: input
    id: core-hash
    attributes:
      label: Core SHA1 Commit Hash
      description: The commit SHA1 hash of your core
      placeholder: Fetch using 'git rev-parse HEAD' in your local CMaNGOS repo
    validations:
      required: true
  - type: input
    id: db-hash
    attributes:
      label: Database SHA1 Commit Hash
      description: The commit SHA1 hash of your database
      placeholder: Fetch using 'git rev-parse HEAD' in your local database repo
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system (including version) are you using for your server environment
    validations:
      required: true
  - type: dropdown
    id: client-version
    attributes:
      label: Client Version
      description: What version(s) of the client does this issue affect?
      options:
        - 1.12.1 (Classic)
        - 2.4.3 (The Burning Crusade)
        - 3.3.5a (Wrath of the Lich King)
    validations:
      required: true
